# site settings
title: TEDSIG
subtitle: Speculative Library Futures
description: Call for Proposals - Closed<br/>Accepted Proposals, Due - February 15, 2021<br/>Publication - Late March 2021
url: https://futures.alaoweb.org
author: TEDSIG

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/dzoladz/tedsig-futures
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

#twitter & open graph card
twitter_site: '@alaotedsig'
twitter_creator: '@derek_zoladz'
opengraph_description: 'This call for proposals seeks submissions for a web-based publication on speculative library futures.'
opengraph_image: og_futures_cone.png


# build settings
markdown: kramdown

sass:
  style: compressed

# Controls
showMenu: true
showTiles: true
showSummary: true
